#!/usr/bin/env bash
#
# Posts an automated reply on an apollographql/apollo-ios issue under a bot
# identity and prints the resulting comment URL.
#
# Two mechanisms, tried in order:
#   1. UPSTREAM_TOKEN      a GitHub App token with issues:write on the upstream repo;
#                          the comment is posted directly as that app.
#   2. UPSTREAM_DISPATCH_TOKEN
#                          any token with write access to the upstream repo; a
#                          `post-triage-reply` repository_dispatch is sent and the
#                          upstream relay workflow posts the comment with its own
#                          GITHUB_TOKEN (author: github-actions[bot]). The script then
#                          waits for the comment to appear so it can return its URL.
# A person's PAT may be used for (2) because it only fires the event; it never
# authors the comment.
#
# Usage: post-upstream-reply.sh <issue-number> <body-file>
# Environment: UPSTREAM_REPO (default apollographql/apollo-ios), RUN_URL,
#              CONFIRM_TIMEOUT_SECONDS (default 180)
# Exit 0 with the comment URL on stdout, 1 if nothing was posted, 2 if the
# dispatch was sent but the comment could not be confirmed in time.

set -euo pipefail

n="${1:?issue number}"; body_file="${2:?body file}"
UPSTREAM_REPO="${UPSTREAM_REPO:-apollographql/apollo-ios}"
CONFIRM_TIMEOUT_SECONDS="${CONFIRM_TIMEOUT_SECONDS:-180}"
[[ "$n" =~ ^[0-9]+$ ]] || { echo "issue number must be an integer" >&2; exit 1; }
[[ -s "$body_file" ]] || { echo "body file is empty" >&2; exit 1; }

footer=$'\n\n---\n_This reply was generated by an automated assistant and has not yet been reviewed by a maintainer. If it does not resolve your issue, reply here and we will take a look._'

if [[ -n "${UPSTREAM_TOKEN:-}" ]]; then
  { cat "$body_file"; printf '%s' "$footer"; } \
    | GH_TOKEN="$UPSTREAM_TOKEN" gh issue comment "$n" --repo "$UPSTREAM_REPO" --body-file -
  exit 0
fi

if [[ -z "${UPSTREAM_DISPATCH_TOKEN:-}" ]]; then
  echo "No upstream posting mechanism configured." >&2
  exit 1
fi

# A hidden marker lets us find the comment the relay posts.
marker="<!-- triage-reply $(date -u +%s)-$$ -->"
body="$(cat "$body_file"; printf '%s\n%s' "$footer" "$marker")"
jq -n --arg n "$n" --arg body "$body" --arg run "${RUN_URL:-}" \
  '{event_type: "post-triage-reply", client_payload: {issue_number: ($n|tonumber), body: $body, run_url: $run}}' \
  | GH_TOKEN="$UPSTREAM_DISPATCH_TOKEN" gh api -X POST "repos/${UPSTREAM_REPO}/dispatches" --input - >/dev/null
echo "Dispatched post-triage-reply for #$n; waiting for the relay to post it." >&2

start=$(date +%s)
while true; do
  url="$(GH_TOKEN="$UPSTREAM_DISPATCH_TOKEN" gh api "repos/${UPSTREAM_REPO}/issues/${n}/comments?per_page=100&sort=created&direction=desc" \
    --jq --arg m "$marker" '.[] | select(.body | contains($m)) | .html_url' 2>/dev/null | head -1 || true)"
  if [[ -n "$url" ]]; then
    echo "$url"
    exit 0
  fi
  if (( $(date +%s) - start > CONFIRM_TIMEOUT_SECONDS )); then
    echo "Dispatch sent but no comment appeared within ${CONFIRM_TIMEOUT_SECONDS}s. Is the relay workflow present on ${UPSTREAM_REPO}'s default branch?" >&2
    exit 2
  fi
  sleep 10
done
