[package]
name = "apollo-codegen-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
graphql-compiler = { path = "../graphql-compiler" }
ir = { path = "../ir" }
utilities = { path = "../utilities" }
template-string = { path = "../template-string" }
indexmap = { workspace = true }
regex = { workspace = true }
bitflags = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
apollo-compiler = { workspace = true }
rayon = { workspace = true }
sha2 = { workspace = true }
globset = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
tempfile = "3"
pretty_assertions = "1.4"

[[bin]]
name = "ir-compare"
path = "src/bin/ir_compare.rs"

[lints]
workspace = true
