name: "Run CocoaPods Integration Tests"
description: Runs CocoaPods Integration Tests against the apollo-ios repo
runs:
  using: "composite"
  steps:
  - name: CocoaPods - Install
    shell: bash
    working-directory: Tests/CodegenCLITests/pod-install-test/
    run: |
      pod install --verbose
  - name: CocoaPods - CLI Test (init)
    shell: bash
    working-directory: Tests/CodegenCLITests/pod-install-test/
    run: |
      ./Pods/Apollo/apollo-ios-cli init --schema-namespace NewTestSchema --module-type other
  - name: CocoaPods - CLI Test (generate)
    shell: bash
    working-directory: Tests/CodegenCLITests/pod-install-test/
    run: |
      ./Pods/Apollo/apollo-ios-cli generate
    