name: "Run Tuist Generation"
description: Installs and run Tuist to generate Xcode projects
runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@v3
    - name: Run Tuist
      shell: bash
      run: tuist generate
