name: "Run Tuist Generation"
description: Installs and run Tuist to generate Xcode projects
runs:
  using: "composite"
  steps:
    - name: Run Tuist
      shell: bash
      run: |
        ./scripts/install-tuist.sh
        tuist generate
