name: "Repo Dispatch"
description: "Sends a dispatch to another repo to trigger a workflow."
inputs:
  access-token:
    description: "The Personal Access Token with proper permissions to the given repository."
    required: true
  repo:
    description: "The name of the repository to dispatch to."
    required: true
  client-payload:
    description: "The JSON client payload to send with the dispatch."
    required: true
runs:
  using: "composite"
  steps:
    - name: Repository Dispatch
      shell: bash
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.access-token }}" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/apollographql/${{ inputs.repo }}/dispatches \
          -d "${{ inputs.client-payload }}"