# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'pod-install-test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for codegen-cli-issue
  pod 'Apollo', :path => "../../../apollo-ios/"
  pod 'ApolloTestSupport', :path => "../../../apollo-ios/"
end

post_install do |installer|
    system('mkdir Pods/Apollo')
    system('cp "../../../../../apollo-ios/apollo-ios-cli" ./Pods/Apollo')
end
