# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'pod-install-test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for codegen-cli-issue
  if ENV['GITHUB_REPOSITORY'] != 'apollographql/apollo-ios-dev'
    pod 'Apollo', :git => "https://github.com/#{ENV['GITHUB_REPOSITORY']}.git", :commit => ENV['APOLLO_IOS_SHA']
    pod 'ApolloTestSupport', :git => "https://github.com/#{ENV['GITHUB_REPOSITORY']}.git", :commit => ENV['APOLLO_IOS_SHA']
  else
    pod 'Apollo', :git => 'https://github.com/apollographql/apollo-ios.git', :commit => ENV['APOLLO_IOS_SHA']
    pod 'ApolloTestSupport', :git => 'https://github.com/apollographql/apollo-ios.git', :commit => ENV['APOLLO_IOS_SHA']
  end
end
