name: "Build and Run Unit Tests"
description: Builds and runs unit tests for given scheme and test plan
inputs:
  destination:
    description: "The destination of the build, can include things like platform, architecture, OS, name etc."
    required: true
  scheme:
    description: "The Xcode scheme to build and test against."
    required: true
  test-plan:
    description: "The test plan to use for testing."
    required: true
runs:
  using: "composite"
  steps:
  - name: Build and Test
    shell: bash
    run: |
      xcodebuild clean test -resultBundlePath TestResults/ResultBundle.xcresult -derivedDataPath DerivedData -workspace "ApolloDev.xcworkspace" -scheme "${{ inputs.scheme }}" -destination "${{ inputs.destination }}" -testPlan "${{ inputs.test-plan }}" | xcbeautify