// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public protocol SelectionSet: ApolloAPI.SelectionSet & ApolloAPI.RootSelectionSet
where Schema == GitHubAPI.SchemaMetadata {}

public protocol InlineFragment: ApolloAPI.SelectionSet & ApolloAPI.InlineFragment
where Schema == GitHubAPI.SchemaMetadata {}

public protocol MutableSelectionSet: ApolloAPI.MutableRootSelectionSet
where Schema == GitHubAPI.SchemaMetadata {}

public protocol MutableInlineFragment: ApolloAPI.MutableSelectionSet & ApolloAPI.InlineFragment
where Schema == GitHubAPI.SchemaMetadata {}

public enum SchemaMetadata: ApolloAPI.SchemaMetadata {
  public static let configuration: any ApolloAPI.SchemaConfiguration.Type = SchemaConfiguration.self

  private static let objectTypeMap: [String: ApolloAPI.Object] = [
    "AddedToProjectEvent": GitHubAPI.Objects.AddedToProjectEvent,
    "App": GitHubAPI.Objects.App,
    "AssignedEvent": GitHubAPI.Objects.AssignedEvent,
    "AutomaticBaseChangeFailedEvent": GitHubAPI.Objects.AutomaticBaseChangeFailedEvent,
    "AutomaticBaseChangeSucceededEvent": GitHubAPI.Objects.AutomaticBaseChangeSucceededEvent,
    "BaseRefChangedEvent": GitHubAPI.Objects.BaseRefChangedEvent,
    "BaseRefForcePushedEvent": GitHubAPI.Objects.BaseRefForcePushedEvent,
    "Blob": GitHubAPI.Objects.Blob,
    "Bot": GitHubAPI.Objects.Bot,
    "BranchProtectionRule": GitHubAPI.Objects.BranchProtectionRule,
    "CheckRun": GitHubAPI.Objects.CheckRun,
    "CheckSuite": GitHubAPI.Objects.CheckSuite,
    "ClosedEvent": GitHubAPI.Objects.ClosedEvent,
    "CodeOfConduct": GitHubAPI.Objects.CodeOfConduct,
    "CommentDeletedEvent": GitHubAPI.Objects.CommentDeletedEvent,
    "Commit": GitHubAPI.Objects.Commit,
    "CommitComment": GitHubAPI.Objects.CommitComment,
    "CommitCommentThread": GitHubAPI.Objects.CommitCommentThread,
    "ConnectedEvent": GitHubAPI.Objects.ConnectedEvent,
    "ConvertToDraftEvent": GitHubAPI.Objects.ConvertToDraftEvent,
    "ConvertedNoteToIssueEvent": GitHubAPI.Objects.ConvertedNoteToIssueEvent,
    "CrossReferencedEvent": GitHubAPI.Objects.CrossReferencedEvent,
    "DemilestonedEvent": GitHubAPI.Objects.DemilestonedEvent,
    "DependencyGraphManifest": GitHubAPI.Objects.DependencyGraphManifest,
    "DeployKey": GitHubAPI.Objects.DeployKey,
    "DeployedEvent": GitHubAPI.Objects.DeployedEvent,
    "Deployment": GitHubAPI.Objects.Deployment,
    "DeploymentEnvironmentChangedEvent": GitHubAPI.Objects.DeploymentEnvironmentChangedEvent,
    "DeploymentStatus": GitHubAPI.Objects.DeploymentStatus,
    "DisconnectedEvent": GitHubAPI.Objects.DisconnectedEvent,
    "Enterprise": GitHubAPI.Objects.Enterprise,
    "EnterpriseAdministratorInvitation": GitHubAPI.Objects.EnterpriseAdministratorInvitation,
    "EnterpriseIdentityProvider": GitHubAPI.Objects.EnterpriseIdentityProvider,
    "EnterpriseRepositoryInfo": GitHubAPI.Objects.EnterpriseRepositoryInfo,
    "EnterpriseServerInstallation": GitHubAPI.Objects.EnterpriseServerInstallation,
    "EnterpriseServerUserAccount": GitHubAPI.Objects.EnterpriseServerUserAccount,
    "EnterpriseServerUserAccountEmail": GitHubAPI.Objects.EnterpriseServerUserAccountEmail,
    "EnterpriseServerUserAccountsUpload": GitHubAPI.Objects.EnterpriseServerUserAccountsUpload,
    "EnterpriseUserAccount": GitHubAPI.Objects.EnterpriseUserAccount,
    "ExternalIdentity": GitHubAPI.Objects.ExternalIdentity,
    "Gist": GitHubAPI.Objects.Gist,
    "GistComment": GitHubAPI.Objects.GistComment,
    "HeadRefDeletedEvent": GitHubAPI.Objects.HeadRefDeletedEvent,
    "HeadRefForcePushedEvent": GitHubAPI.Objects.HeadRefForcePushedEvent,
    "HeadRefRestoredEvent": GitHubAPI.Objects.HeadRefRestoredEvent,
    "IpAllowListEntry": GitHubAPI.Objects.IpAllowListEntry,
    "Issue": GitHubAPI.Objects.Issue,
    "IssueComment": GitHubAPI.Objects.IssueComment,
    "IssueCommentConnection": GitHubAPI.Objects.IssueCommentConnection,
    "IssueConnection": GitHubAPI.Objects.IssueConnection,
    "Label": GitHubAPI.Objects.Label,
    "LabeledEvent": GitHubAPI.Objects.LabeledEvent,
    "Language": GitHubAPI.Objects.Language,
    "License": GitHubAPI.Objects.License,
    "LockedEvent": GitHubAPI.Objects.LockedEvent,
    "Mannequin": GitHubAPI.Objects.Mannequin,
    "MarkedAsDuplicateEvent": GitHubAPI.Objects.MarkedAsDuplicateEvent,
    "MarketplaceCategory": GitHubAPI.Objects.MarketplaceCategory,
    "MarketplaceListing": GitHubAPI.Objects.MarketplaceListing,
    "MembersCanDeleteReposClearAuditEntry": GitHubAPI.Objects.MembersCanDeleteReposClearAuditEntry,
    "MembersCanDeleteReposDisableAuditEntry": GitHubAPI.Objects.MembersCanDeleteReposDisableAuditEntry,
    "MembersCanDeleteReposEnableAuditEntry": GitHubAPI.Objects.MembersCanDeleteReposEnableAuditEntry,
    "MentionedEvent": GitHubAPI.Objects.MentionedEvent,
    "MergedEvent": GitHubAPI.Objects.MergedEvent,
    "Milestone": GitHubAPI.Objects.Milestone,
    "MilestonedEvent": GitHubAPI.Objects.MilestonedEvent,
    "MovedColumnsInProjectEvent": GitHubAPI.Objects.MovedColumnsInProjectEvent,
    "OauthApplicationCreateAuditEntry": GitHubAPI.Objects.OauthApplicationCreateAuditEntry,
    "OrgAddBillingManagerAuditEntry": GitHubAPI.Objects.OrgAddBillingManagerAuditEntry,
    "OrgAddMemberAuditEntry": GitHubAPI.Objects.OrgAddMemberAuditEntry,
    "OrgBlockUserAuditEntry": GitHubAPI.Objects.OrgBlockUserAuditEntry,
    "OrgConfigDisableCollaboratorsOnlyAuditEntry": GitHubAPI.Objects.OrgConfigDisableCollaboratorsOnlyAuditEntry,
    "OrgConfigEnableCollaboratorsOnlyAuditEntry": GitHubAPI.Objects.OrgConfigEnableCollaboratorsOnlyAuditEntry,
    "OrgCreateAuditEntry": GitHubAPI.Objects.OrgCreateAuditEntry,
    "OrgDisableOauthAppRestrictionsAuditEntry": GitHubAPI.Objects.OrgDisableOauthAppRestrictionsAuditEntry,
    "OrgDisableSamlAuditEntry": GitHubAPI.Objects.OrgDisableSamlAuditEntry,
    "OrgDisableTwoFactorRequirementAuditEntry": GitHubAPI.Objects.OrgDisableTwoFactorRequirementAuditEntry,
    "OrgEnableOauthAppRestrictionsAuditEntry": GitHubAPI.Objects.OrgEnableOauthAppRestrictionsAuditEntry,
    "OrgEnableSamlAuditEntry": GitHubAPI.Objects.OrgEnableSamlAuditEntry,
    "OrgEnableTwoFactorRequirementAuditEntry": GitHubAPI.Objects.OrgEnableTwoFactorRequirementAuditEntry,
    "OrgInviteMemberAuditEntry": GitHubAPI.Objects.OrgInviteMemberAuditEntry,
    "OrgInviteToBusinessAuditEntry": GitHubAPI.Objects.OrgInviteToBusinessAuditEntry,
    "OrgOauthAppAccessApprovedAuditEntry": GitHubAPI.Objects.OrgOauthAppAccessApprovedAuditEntry,
    "OrgOauthAppAccessDeniedAuditEntry": GitHubAPI.Objects.OrgOauthAppAccessDeniedAuditEntry,
    "OrgOauthAppAccessRequestedAuditEntry": GitHubAPI.Objects.OrgOauthAppAccessRequestedAuditEntry,
    "OrgRemoveBillingManagerAuditEntry": GitHubAPI.Objects.OrgRemoveBillingManagerAuditEntry,
    "OrgRemoveMemberAuditEntry": GitHubAPI.Objects.OrgRemoveMemberAuditEntry,
    "OrgRemoveOutsideCollaboratorAuditEntry": GitHubAPI.Objects.OrgRemoveOutsideCollaboratorAuditEntry,
    "OrgRestoreMemberAuditEntry": GitHubAPI.Objects.OrgRestoreMemberAuditEntry,
    "OrgRestoreMemberMembershipOrganizationAuditEntryData": GitHubAPI.Objects.OrgRestoreMemberMembershipOrganizationAuditEntryData,
    "OrgRestoreMemberMembershipRepositoryAuditEntryData": GitHubAPI.Objects.OrgRestoreMemberMembershipRepositoryAuditEntryData,
    "OrgRestoreMemberMembershipTeamAuditEntryData": GitHubAPI.Objects.OrgRestoreMemberMembershipTeamAuditEntryData,
    "OrgUnblockUserAuditEntry": GitHubAPI.Objects.OrgUnblockUserAuditEntry,
    "OrgUpdateDefaultRepositoryPermissionAuditEntry": GitHubAPI.Objects.OrgUpdateDefaultRepositoryPermissionAuditEntry,
    "OrgUpdateMemberAuditEntry": GitHubAPI.Objects.OrgUpdateMemberAuditEntry,
    "OrgUpdateMemberRepositoryCreationPermissionAuditEntry": GitHubAPI.Objects.OrgUpdateMemberRepositoryCreationPermissionAuditEntry,
    "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry": GitHubAPI.Objects.OrgUpdateMemberRepositoryInvitationPermissionAuditEntry,
    "Organization": GitHubAPI.Objects.Organization,
    "OrganizationIdentityProvider": GitHubAPI.Objects.OrganizationIdentityProvider,
    "OrganizationInvitation": GitHubAPI.Objects.OrganizationInvitation,
    "Package": GitHubAPI.Objects.Package,
    "PackageFile": GitHubAPI.Objects.PackageFile,
    "PackageTag": GitHubAPI.Objects.PackageTag,
    "PackageVersion": GitHubAPI.Objects.PackageVersion,
    "PinnedEvent": GitHubAPI.Objects.PinnedEvent,
    "PinnedIssue": GitHubAPI.Objects.PinnedIssue,
    "PrivateRepositoryForkingDisableAuditEntry": GitHubAPI.Objects.PrivateRepositoryForkingDisableAuditEntry,
    "PrivateRepositoryForkingEnableAuditEntry": GitHubAPI.Objects.PrivateRepositoryForkingEnableAuditEntry,
    "Project": GitHubAPI.Objects.Project,
    "ProjectCard": GitHubAPI.Objects.ProjectCard,
    "ProjectColumn": GitHubAPI.Objects.ProjectColumn,
    "PublicKey": GitHubAPI.Objects.PublicKey,
    "PullRequest": GitHubAPI.Objects.PullRequest,
    "PullRequestCommit": GitHubAPI.Objects.PullRequestCommit,
    "PullRequestCommitCommentThread": GitHubAPI.Objects.PullRequestCommitCommentThread,
    "PullRequestReview": GitHubAPI.Objects.PullRequestReview,
    "PullRequestReviewComment": GitHubAPI.Objects.PullRequestReviewComment,
    "PullRequestReviewThread": GitHubAPI.Objects.PullRequestReviewThread,
    "Push": GitHubAPI.Objects.Push,
    "PushAllowance": GitHubAPI.Objects.PushAllowance,
    "Query": GitHubAPI.Objects.Query,
    "Reaction": GitHubAPI.Objects.Reaction,
    "ReadyForReviewEvent": GitHubAPI.Objects.ReadyForReviewEvent,
    "Ref": GitHubAPI.Objects.Ref,
    "ReferencedEvent": GitHubAPI.Objects.ReferencedEvent,
    "Release": GitHubAPI.Objects.Release,
    "ReleaseAsset": GitHubAPI.Objects.ReleaseAsset,
    "RemovedFromProjectEvent": GitHubAPI.Objects.RemovedFromProjectEvent,
    "RenamedTitleEvent": GitHubAPI.Objects.RenamedTitleEvent,
    "ReopenedEvent": GitHubAPI.Objects.ReopenedEvent,
    "RepoAccessAuditEntry": GitHubAPI.Objects.RepoAccessAuditEntry,
    "RepoAddMemberAuditEntry": GitHubAPI.Objects.RepoAddMemberAuditEntry,
    "RepoAddTopicAuditEntry": GitHubAPI.Objects.RepoAddTopicAuditEntry,
    "RepoArchivedAuditEntry": GitHubAPI.Objects.RepoArchivedAuditEntry,
    "RepoChangeMergeSettingAuditEntry": GitHubAPI.Objects.RepoChangeMergeSettingAuditEntry,
    "RepoConfigDisableAnonymousGitAccessAuditEntry": GitHubAPI.Objects.RepoConfigDisableAnonymousGitAccessAuditEntry,
    "RepoConfigDisableCollaboratorsOnlyAuditEntry": GitHubAPI.Objects.RepoConfigDisableCollaboratorsOnlyAuditEntry,
    "RepoConfigDisableContributorsOnlyAuditEntry": GitHubAPI.Objects.RepoConfigDisableContributorsOnlyAuditEntry,
    "RepoConfigDisableSockpuppetDisallowedAuditEntry": GitHubAPI.Objects.RepoConfigDisableSockpuppetDisallowedAuditEntry,
    "RepoConfigEnableAnonymousGitAccessAuditEntry": GitHubAPI.Objects.RepoConfigEnableAnonymousGitAccessAuditEntry,
    "RepoConfigEnableCollaboratorsOnlyAuditEntry": GitHubAPI.Objects.RepoConfigEnableCollaboratorsOnlyAuditEntry,
    "RepoConfigEnableContributorsOnlyAuditEntry": GitHubAPI.Objects.RepoConfigEnableContributorsOnlyAuditEntry,
    "RepoConfigEnableSockpuppetDisallowedAuditEntry": GitHubAPI.Objects.RepoConfigEnableSockpuppetDisallowedAuditEntry,
    "RepoConfigLockAnonymousGitAccessAuditEntry": GitHubAPI.Objects.RepoConfigLockAnonymousGitAccessAuditEntry,
    "RepoConfigUnlockAnonymousGitAccessAuditEntry": GitHubAPI.Objects.RepoConfigUnlockAnonymousGitAccessAuditEntry,
    "RepoCreateAuditEntry": GitHubAPI.Objects.RepoCreateAuditEntry,
    "RepoDestroyAuditEntry": GitHubAPI.Objects.RepoDestroyAuditEntry,
    "RepoRemoveMemberAuditEntry": GitHubAPI.Objects.RepoRemoveMemberAuditEntry,
    "RepoRemoveTopicAuditEntry": GitHubAPI.Objects.RepoRemoveTopicAuditEntry,
    "Repository": GitHubAPI.Objects.Repository,
    "RepositoryInvitation": GitHubAPI.Objects.RepositoryInvitation,
    "RepositoryTopic": GitHubAPI.Objects.RepositoryTopic,
    "RepositoryVisibilityChangeDisableAuditEntry": GitHubAPI.Objects.RepositoryVisibilityChangeDisableAuditEntry,
    "RepositoryVisibilityChangeEnableAuditEntry": GitHubAPI.Objects.RepositoryVisibilityChangeEnableAuditEntry,
    "RepositoryVulnerabilityAlert": GitHubAPI.Objects.RepositoryVulnerabilityAlert,
    "ReviewDismissalAllowance": GitHubAPI.Objects.ReviewDismissalAllowance,
    "ReviewDismissedEvent": GitHubAPI.Objects.ReviewDismissedEvent,
    "ReviewRequest": GitHubAPI.Objects.ReviewRequest,
    "ReviewRequestRemovedEvent": GitHubAPI.Objects.ReviewRequestRemovedEvent,
    "ReviewRequestedEvent": GitHubAPI.Objects.ReviewRequestedEvent,
    "SavedReply": GitHubAPI.Objects.SavedReply,
    "SecurityAdvisory": GitHubAPI.Objects.SecurityAdvisory,
    "SponsorsListing": GitHubAPI.Objects.SponsorsListing,
    "SponsorsTier": GitHubAPI.Objects.SponsorsTier,
    "Sponsorship": GitHubAPI.Objects.Sponsorship,
    "Status": GitHubAPI.Objects.Status,
    "StatusCheckRollup": GitHubAPI.Objects.StatusCheckRollup,
    "StatusContext": GitHubAPI.Objects.StatusContext,
    "SubscribedEvent": GitHubAPI.Objects.SubscribedEvent,
    "Tag": GitHubAPI.Objects.Tag,
    "Team": GitHubAPI.Objects.Team,
    "TeamAddMemberAuditEntry": GitHubAPI.Objects.TeamAddMemberAuditEntry,
    "TeamAddRepositoryAuditEntry": GitHubAPI.Objects.TeamAddRepositoryAuditEntry,
    "TeamChangeParentTeamAuditEntry": GitHubAPI.Objects.TeamChangeParentTeamAuditEntry,
    "TeamDiscussion": GitHubAPI.Objects.TeamDiscussion,
    "TeamDiscussionComment": GitHubAPI.Objects.TeamDiscussionComment,
    "TeamRemoveMemberAuditEntry": GitHubAPI.Objects.TeamRemoveMemberAuditEntry,
    "TeamRemoveRepositoryAuditEntry": GitHubAPI.Objects.TeamRemoveRepositoryAuditEntry,
    "Topic": GitHubAPI.Objects.Topic,
    "TransferredEvent": GitHubAPI.Objects.TransferredEvent,
    "Tree": GitHubAPI.Objects.Tree,
    "UnassignedEvent": GitHubAPI.Objects.UnassignedEvent,
    "UnlabeledEvent": GitHubAPI.Objects.UnlabeledEvent,
    "UnlockedEvent": GitHubAPI.Objects.UnlockedEvent,
    "UnmarkedAsDuplicateEvent": GitHubAPI.Objects.UnmarkedAsDuplicateEvent,
    "UnpinnedEvent": GitHubAPI.Objects.UnpinnedEvent,
    "UnsubscribedEvent": GitHubAPI.Objects.UnsubscribedEvent,
    "User": GitHubAPI.Objects.User,
    "UserBlockedEvent": GitHubAPI.Objects.UserBlockedEvent,
    "UserContentEdit": GitHubAPI.Objects.UserContentEdit,
    "UserStatus": GitHubAPI.Objects.UserStatus
  ]

  public static func objectType(forTypename typename: String) -> ApolloAPI.Object? {
    objectTypeMap[typename]
  }
}

public enum Objects {}
public enum Interfaces {}
public enum Unions {}
