name: "Subtree Split and Push"
description: Attempts to split and rejoin the given subtree into the working history, if changes were found also pushes the changes to the subtree repo.
inputs:
  subtree:
    description: "The prefix for the subtree being operated on."
    required: true
  remote:
    description: "The remote repository for the subtree to push to."
    required: true
  target-branch:
    description: "The branch of the remote to push to."
    required: true
  pr-number:
    description: "The number of the PR that triggered this action."
    required: true
  pr-title: 
    description: "The title of the PR that triggered this action."
    required: true
runs:
  using: "composite"
  steps:
  - name: Split and Push ${{ inputs.subtree }}
    shell: bash
    env:
      PR_TITLE: ${{ inputs.pr-title }}
    run: |
      set -euo pipefail
      echo "git: $(git --version)"
      echo "subtree: $(command -v git-subtree)"
      SUBTREE=$(command -v git-subtree)
      export GIT_TRACE=1 GIT_TRACE_SETUP=1 GIT_TRACE_PERFORMANCE=1
      export GIT_TRACE2_EVENT=$PWD/git-trace2.json
      export PS4='+${BASH_SOURCE##*/}:${LINENO}:${FUNCNAME[0]}: '
      git fetch ${{ inputs.remote }} ${{ inputs.target-branch }}
      bash -xuo pipefail "$SUBTREE" pull -P ${{ inputs.subtree }} --squash -m "pull: ${{ inputs.subtree }} - PR #${{ inputs.pr-number }} - $PR_TITLE" ${{ inputs.remote }} ${{ inputs.target-branch }} 2>subtree-debug.sh.log
      splitResult=$(bash -xuo pipefail "$SUBTREE" -P ${{ inputs.subtree }} split --squash --rejoin -m "split: ${{ inputs.subtree }} - PR #${{ inputs.pr-number }} - $PR_TITLE" 2>subtree-debug.sh.log)
      if [ ! -z "$splitResult" ]
      then
        bash -xuo pipefail "$SUBTREE" push -P ${{ inputs.subtree }} ${{ inputs.remote }} ${{ inputs.target-branch }} 2>subtree-debug.sh.log
      fi
