name: "Subtree Split"
description: Splits the given subtree into the working history and outputs the split SHA. Push is handled separately after all subtrees have been split successfully.
inputs:
  subtree:
    description: "The prefix for the subtree being operated on."
    required: true
  remote:
    description: "The remote repository for the subtree to push to."
    required: true
  target-branch:
    description: "The branch of the remote to push to."
    required: true
  pr-number:
    description: "The number of the PR that triggered this action."
    required: true
  pr-title:
    description: "The title of the PR that triggered this action."
    required: true
outputs:
  split-sha:
    description: "The SHA of the split commit, empty if no changes were found."
    value: ${{ steps.split.outputs.split_sha }}
runs:
  using: "composite"
  steps:
  - name: Split ${{ inputs.subtree }}
    id: split
    shell: bash
    env:
      PR_TITLE: ${{ inputs.pr-title }}
    run: |
      echo "git: $(git --version)"
      git fetch ${{ inputs.remote }} ${{ inputs.target-branch }}
      git subtree pull -P ${{ inputs.subtree }} --squash -m "pull: ${{ inputs.subtree }} - PR #${{ inputs.pr-number }} - $PR_TITLE" ${{ inputs.remote }} ${{ inputs.target-branch }}
      splitResult=$(git subtree -P ${{ inputs.subtree }} split --squash --rejoin -m "split: ${{ inputs.subtree }} - PR #${{ inputs.pr-number }} - $PR_TITLE")
      echo "split_sha=$splitResult" >> $GITHUB_OUTPUT
