name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    name: Close and Comment PR
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "We do not accept PRs directly to the 'apollo-ios' repo. All development is done through the 'apollo-ios-dev' repo, please see the CONTRIBUTING guide for more information."