name: Deploy docs to production

on:
  pull_request_target:
    branches:
      - main
    paths:
      - docs/**
    types: [closed]

permissions:
  contents: read

jobs:
  publish:
    if: ${{ github.event.pull_request.merged }}
    permissions:
      contents: read
    uses: apollographql/docs/.github/workflows/publish.yml@main
    secrets:
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
